"""initial_schema

Revision ID: ef6f789c4789
Revises: 
Create Date: 2026-03-14 16:11:02.858042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef6f789c4789'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Skip the alter if daily_summaries doesn't exist yet —
    # it will be created correctly by the next migration or create_all
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'daily_summaries' in inspector.get_table_names():
        op.alter_column('daily_summaries', 'date',
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.Date(),
            existing_nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_summaries', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
